language: java
jdk: 
- oraclejdk8

before_install:
- cd QorderWS

script:
- mvn compile war:war

deploy:
  provider: releases
  api-key: $ travis setup releases
  file: "target/qorderws-pr-SNAPSHOT.war"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true