language: java
jdk:
- oraclejdk8
before_install:
- cd QorderWS
after_success:
- mvn compile war:war
deploy:
  provider: releases
  api_key:
    secure: cIt5U7nP/FJEIgAtQ4dR7jqleiKIf5LSzK74AEfxKjNH01SkWdRhiHR1eeJutkYYPgjgrpUSMH5kFXKZcnTNBUIhV8QGOFmnYPJqHRBHXJW3Y+tio3t+cIB3+XeSWb8RmvOpcYHCnVz2s86OuBmWhqTk0fvIygpGC7RVFZnhDzY=
  file: /home/travis/build/Qorder/QorderWS/QorderWS/target/*.war
  skip_cleanup: true
  on:
    repo: Qorder/QorderWS
    tags: true
    all_branches: true
env:
  global:
    secure: sfh9bMrFaBm8t3OGkTwRIOLbdlaF1XtxqN9sRRaMMJ5sqEvZ1urxWAUMY7EZ4eXlhAKXGBGi3HSHSXaMPm6dVvLLmDYAsO8N22DEUAgdX6tIecZrPnEJJJC0aD7MHwFAH6JySI8SGqyYX6qdx8idg5+v6mXkBeAxVvp1vlYiV4s=
